package-lock.json, package.json, webpack.config.js
This only affects local development and is probably not too big a deal, but updating webpack bits mitigates CVE-2018-3774 (https://nvd.nist.gov/vuln/detail/CVE-2018-3774).
NOTE: this also required switching from Uglify to Terser, since the Webpack Uglify plugin stopped using Uglify-ES (it’s deprecated). It’s been replaced by Terser for ES 2015+ syntax.
=> Security: Update all webpack-related dependencies

package-lock.json
See https://nvd.nist.gov/vuln/detail/CVE-2018-16487. I think this shouldn’t actually affect the usage of Lodash here (from webpack-dev-server), but it's buried deep enough that I'm not really sure. Better to be safe and upgrade.
=> Upgrade Lodash to address CVE-2018-16487

index.html, index.js, lib/fix-google-html.js, lib/log-tree.js, lib/rehype-to-remark-with-spaces.js
This fixes a bunch of small bugs I noticed while updating #6:
- Logging module now puts quotes around text so you can see whitespace at the end of a value.
- Wrap text in the output area so it’s actually readable.
- Make sure space at the *end* of text tokens is preserved. (We only did this at the start before, which was making a few critical errors.
- Remove excess space around paragraphs, headings, lists, and other blocks. Google Docs throws line breaks in between those items, and the markdown conversion turns both the line break AND the block element into line breaks, resulting in doubled-up breaks all over the place.
=> General Cleanup

index.js
=> Remove excess whitespace at the start of list items.

index.js
This is a nicety that helps the markdown itself be more readable (but doesn't affect its conversion to other formats, like HTML).
=> Ensure headings are preceded by two blank lines

package.json
`package.json` was listing the incorrect license (it’s correct everywhere else in the codebase).
Fixes #17.
=> Fix incorrect license identifier in `package.json`

lib/fix-google-html.js
I'm pretty sure nested bold and italic used to work before, but it seems to have regressed at some point (I ran into this while working on #52). This makes them work (again?).
It’s a little complex because it has to account for some funky cases around spaces at the start or end of some kinds of markup.
=> Fix support for nested bold/italic formatting

lib/fix-google-html.js
Somewhere along the line, support for hard line breaks inside paragraphs, list items, etc. broke. Found while working on #52.
=> Fix support for non-paragraph line breaks

lib/fix-google-html.js
I thought this supported struck out text before, but apparently not. Found while working on #52.
=> Support stike-through formatting

.github/workflows/update-fixtures.yml
Since most of our fixtures are actual Google Docs docs, we need to periodically update our local copies in case the copy/export formats for Google Docs change. This adds a scheduled workflow to download fixtures, and if they've changed, create a PR.
=> Automatically update Google Docs fixtures

.github/workflows/update-fixtures.yml
Whoops, the update-fixtures workflow needs Node.js v18+.
=> Run update workflow with correct Node.js version

.npmrc, package-lock.json, package.json
Tests recently started failing in GitHub actions, and it's because the pre-installed version of Chrome and the version of Chromedriver specified in `package.json` fell out of sync. This installs the latest Chromedriver, but also adds some NPM configuration options to make this future-proof by installing the correct, matching versions of Chromedriver and Chromium itself, rather than the specific on in `package.json`.
As a side note, it *seems* like we should only need to specify `include_chromium=true` (so we have a version of Chromium that matches Chromedriver), but that setting is ignored unless `detect_chromedriver_version=true` is also set, which seems counterintuitive to me (if you are installing a compatible chromium, you shouldn’t need to detect the version, since you are installing …
=> Install correct Chromedriver version

.github/workflows/discussion-accessibility.yml
This sets up GitHub's official action to check image alt text in issues, PRs, and discussions. See more about it in this blog post: https://github.blog/2023-06-12-make-your-github-projects-more-accessible-with-accessibility-alt-text-bot/
I haven't tried this on any other repos yet, but it looks like a useful tool.
=> Add GitHub alt text bot

.github/dependabot.yml
I think I hadn't configured this previously because of interest in publishing this as a library on NPM (#42), but to be honest I don't recall exactly. In any case, I realized today I could create separate update configuration for dev and production dependencies, which solves any issues I think I would have been concerned about. (There are no production dependencies right now, but I'll have to shift hast/unified/etc. to production to publish on NPM, at which point the separate configs will matter.)
=> Turn on Dependabot for NPM

.editorconfig, .github/workflows/discussion-accessibility.yml, index.html, lib/log-tree.js, lib/rehype-to-remark-with-spaces.js
This is just a minor formatting cleanup to remove trailing spaces from code files (this doesn't affect Markdown files, where trailing spaces are significant).
=> Clean up trailing spaces

.gitignore, README.md, index.html, index.js, package.json, test/e2e/basic.test.js, test/support/utils.js, wdio.conf.base.js, wdio.conf.e2e.js
Hello! What a delightful tool this is; thank you so much for writing it!
I often want to download my Markdown after I get it, so this adds a download button in browsers that support it using the [File](https://developer.mozilla.org/en-US/docs/Web/API/File) and [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) APIs (i.e. just about every browser for nearly ever).
Download code is based off of [this source](https://javascript.plainenglish.io/javascript-create-file-c36f8bccb3be); not sure how much you care about attribution for something so trivial/atomic, but just want to cite my sources.
I had to do a little reformatting but nothing major (button absolutely positioned => container absolutely positioned that now has two buttons).
=> Add download button

.github/workflows/update-fixtures.yml
The PRs created by the `update-fixtures` action need a custom token in order to trigger the CI workflows so they get tested (e.g. #86 did not get tests). This adds a tightly scoped PAT that should let the workflow create PRs that then run workflows.
More docs here: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
=> Use PAT to create automatic PRs

lib/fix-google-html.js, test/fixtures/lists.expected.md, test/unit/convert.test.js
When you copy checklists from a Google Doc, you get some funky markup that doesn't translate very well to Markdown (and it's different in different browsers, too). This identifies that markup and turns it into lists with real checkboxes, which then convert correctly to GitHub-Flavored Markdown checklists like:
```md
```
Fixes #57.
=> Add support for checklists

.github/workflows/update-fixtures.yml, .gitignore, package-lock.json, package.json, scripts/download-fixtures.js
This supersedes #83. It specifies the minimum required version of Node.js in `package.json` (I should have done that long ago!) and ignores various files for specifying the Node.js version in git, so we don't lock developers into a particular version (since we *intend* to eventually get project into NPM as a library and/or CLI tool and not just a web page, we don't want to lock in a specific version).
It also adds `undici` as a dev dependency so that all the dev scripts actually work on all the versions of Node.js this package is meant to support, which was the original driving issue for #83.
=> Specify supported versions of Node.js

.github/dependabot.yml
It turns out WebdriverIO tends to treat interfaces between their packages as private and not subject to semver rules, so you need to be careful about updating them together.
=> Ensure WebdriverIO Dependabot updates are grouped

.editorconfig, .eslintrc.json, .github/dependabot.yml, .github/workflows/ci.yml, .gitignore, .prettierignore, .prettierrc, README.md, index.js, lib/convert.js, lib/css.js, lib/fix-google-html.js, lib/log-tree.js, lib/rehype-to-remark-with-spaces.js, package-lock.json, package.json, scripts/download-fixtures.js, test/e2e/basic.test.js, test/support/fixtures.js, test/support/utils.js, test/support/wdio-webpack-dev-server.js, test/unit/convert.test.js, test/unit/css.test.js, wdio.conf.base.js, wdio.conf.e2e.js, wdio.conf.unit.js, webpack.config.cjs
This supersedes #103. There are no real issues with that PR, but there have been a bunch of source changes since it was proposed that cause conflicts. It's easier to copy the configs over and re-correct things than adapt that branch.
Starting with just ESLint and testing CI, then will add Prettier.
=> Add code linting and CI checks

scripts/download-fixtures.js
We've gotten a few fixture updates that alternately added and removed an `si` property that is an empty string (e.g. #150, #151), so just drop it if it's empty to reduce pointless updates.
=> Ignore `si` property in slice clip fixtures

.eslintrc.json, .github/workflows/ci.yml, .github/workflows/publish-gh-pages.yml, .github/workflows/update-fixtures.yml, package-lock.json, package.json
These are required prerequisites to ESLint v9 (see #198). Node.js 16 is no longer officially supported and it's time to move off it anyhow.
=> Upgrade Node.js 18, ESLint plugins to latest

package-lock.json, package.json, scripts/download-fixtures.js
Now that we require Node.js 18+ (#199), undici is built-in and we don't need it as a separate dependency.
=> Remove undici dependency

index.html, scripts/download-fixtures.js, test/fixtures/headings-with-inline-formatting.copy.gdocsliceclip.json, test/fixtures/headings-with-inline-formatting.copy.html, test/fixtures/headings-with-inline-formatting.expected.md, test/fixtures/headings-with-inline-formatting.export.html
When there's bold formatting in headings, we sometimes lose it because browsers normalize the styling and DOM structure when pasting content into a contenteditable node (which is how we currently capture a paste from Google Docs). Specifically, WebKit- and Chromium- based browsers would see that headings are already bold in the user agent stylesheet, and then normalize out all the bold formatting info in the actual DOM and CSS that gets pasted. This solves the issue by "resetting" the styling on headings inside the input area.
This supersedes #158, which took a way more complicated approach to the problem before I realized we could just style input area to prevent normalization in the first place. 🤦  This also has none of the weird edge cases and caveats that complex approach did. 
Fixes …
=> Support bold text in headings, take 2

index.html, index.js, lib-ui/index.js, lib-ui/settings.js, lib/convert.js, lib/fix-google-html.js, lib/slice-clip.js, package.json, scripts/download-fixtures.js, test/fixtures/suggestions.copy.gdocsliceclip.json, test/fixtures/suggestions.copy.html, test/fixtures/suggestions.expected.accept.md, test/fixtures/suggestions.expected.md, test/fixtures/suggestions.expected.show.md, test/fixtures/suggestions.export.html, test/unit/convert.test.js, wdio.conf.e2e.js, webpack.config.cjs
Fixes #194.
This adds intentional handling for suggested changes. Before, if there were suggestions in the text, we'd show them in a totally undifferentiated way right next to the original text, which could make things appear totally garbled.
For example, this test doc:
Gets this markdown output:
```markdown
This is a test of sugargested changes toin documents.
This tests some **suggested changes** that overlap formatting boundaries.
```
This is because the HTML that Google Docs puts on the pasteboard doesn’t have any info about the suggestions and shows both the suggested insertions and the text that would be deleted right alongside each other. However, the Slice Clip data *does* have info about the suggestions, so we use that to figure out where insertions and deletions go in the text. …
=> Handle suggested changes

lib/convert.js, lib/fix-google-html.js, lib/slice-clip.js, test/fixtures/internal-links.expected.md
We already support links to headings in the document, but links to bookmarks have been hard because the GDocs HTML format does not include the locations of the bookmarks. In #213 we added tooling that makes it much easier to figure out where in the text objects from the Slice Clip format belong, so now we can put the bookmarks in the right place, which then allows us to link to them.
Fixes #134.
=> Support links to bookmarks in the document

lib/fix-google-html.js, lib/slice-clip.js, scripts/download-fixtures.js, test/fixtures/titles-and-empty-headings.copy.gdocsliceclip.json, test/fixtures/titles-and-empty-headings.copy.html, test/fixtures/titles-and-empty-headings.expected.md, test/fixtures/titles-and-empty-headings.export.html, test/unit/convert.test.js
The previous heading finding algorithm for slice clips wound up with mismatches if a document included a title (which is a heading level 100 in the slice clip, but plain text in HTML) or headings that are empty (definitely a weird case; these don't show up at all in the HTML). This implements a new, more strict algorithm that also surfaces more info about the headings.
Fixes #215.
=> Keep heading IDs in docs w/ titles, empty headings

README.md, lib/fix-google-html.js, package.json, test/unit/convert.test.js
When copying content from Google Docs, browsers add HTML comments `` and `` to mark the copied content. These markers are not part of the actual document content and show up in the final markdown output.
This PR:
- Adds a new `removeFragmentMarkers` function that removes these browser-added HTML comments
- Integrates the cleanup into the existing `cleanGoogleHtml` pipeline
- Preserves all other HTML comments that might be meaningful
The change improves the quality of the output markdown by removing unnecessary markup that browsers add during the copy/paste process.
Example of the issue:
```markdown
Some content here
```
Becomes just:
```markdown
Some content here
```
=> Remove browser-added fragment markers from clipboard content

README.md, lib/fix-google-html.js, package.json, scripts/download-fixtures.js, test/fixtures/non-text-between-code.copy.gdocsliceclip.json, test/fixtures/non-text-between-code.copy.html, test/fixtures/non-text-between-code.expected.md, test/fixtures/non-text-between-code.export.html, test/unit/convert.test.js
This fixes images failing to be converted when they are in the middle of code blocks or are converted to an inline code block due to formatting.
=> Fix images being interpreted as code blocks and inline code blocks

scripts/download-fixtures.js, test/fixtures/non-text-between-code.copy.html, test/fixtures/non-text-between-code.export.html
The asset URLs in the Google Docs HTML (both copied and exported) include a unique-to-the-user key (presumably anonymized/hashed in some way). This meant each time we tried to refresh fixtures with images, we'd get a different result (since we are not logged in, we are a different user every time). This replaces the unique part of the asset URLs with a consistent key so our fixtures aren't pointlessly changing.
Obviates #284.
=> Clean up asset URLs in fixtures

wdio.conf.base.js, wdio.conf.e2e.js, wdio.conf.unit.js
The `defineConfig` function was introduced in a recent version of wdio (see #290) and is the new recommended way to set up configuration.
=> Use new `defineConfig` feature in wdio
